# Generated by Django 2.1.8 on 2019-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pan_number', models.IntegerField()),
                ('gst_number', models.IntegerField()),
            ],
        ),
    ]
